#!/bin/bash

# - https://toronto.ctvnews.ca/male-victim-injured-after-shooting-in-west-end-1.4645024
# - https://twitter.com/hashtag/GO2011710
# - http://c4s.torontopolice.on.ca/
# - https://www.hexagonsafetyinfrastructure.com/case-studies/tps-integrates-location-and-navigation-using-mobile-cad
# - https://developers.arcgis.com/rest/users-groups-and-items/common-parameters.htm
# - http://resources.esri.com/help/9.3/arcgisserver/apis/rest/index-9-3.html?query.html
# - https://gist.github.com/patcon/955c62fbaed50bbdd9cf3e34acb170b2
# - https://github.com/patcon
# - https://github.com/gnomon-/toronto-fire-CAD

declare -i now aft ret sleep
declare    dir_data fn dstdir tmpdir tmp_suff
declare -a opts_{curl,tps,ephemeral}

dir_data=/home/gnomon/.toronto-police-CAD
fn='calls-for-service'
tmp_suff='.in_use'

opts_curl=( \
  '-vvv'
  '--fail'
)

opts_tps=( \
  '--url'  'https://c4s.torontopolice.on.ca/arcgis/rest/services/CADPublic/C4S/MapServer/0/query'
  '--get'
  '--data' 'num=1000'
  '--data' 'f=json'
  '--data' 'returnGeometry=true'
  '--data' 'spatialRel=esriSpatialRelIntersects'
  '--data-urlencode' 'where=1=1'
  '--data-urlencode' 'outFields=ATSCENE_TS,DGROUP,TYP_ENG,XSTREETS,OBJECTID,Shape'
)

if [[ ! -d $dir_data ]]; then
	exit 1
fi

printf -v now '%(%s)T' -1
dstdir=${dir_data}/${now}-$$-${RANDOM}
tmpdir=${dstdir}${tmp_suff}

mkdir -- "$tmpdir" || exit 2

opts_ephemeral=( \
  '--dump-header' "${tmpdir}/${fn}.headers"
  '--output'      "${tmpdir}/${fn}.json"
  '--stderr'      "${tmpdir}/${fn}.log"
)

curl "${opts_curl[@]}" "${opts_tps[@]}" "${opts_ephemeral[@]}"
printf '%s\n' "$?" >> "${tmpdir}/${fn}.ret"

mv -- "$tmpdir" "$dstdir" || exit 3
